convert image.pfm image.jpg 
convert image1.pfm image1.jpg 
convert image2.pfm image2.jpg 
convert image3.pfm image3.jpg 
convert image4.pfm image4.jpg 
convert image5.pfm image5.jpg 
convert image6.pfm image6.jpg 
convert image7.pfm image7.jpg 
convert image8.pfm image8.jpg 
convert image9.pfm image9.jpg 
convert image10.pfm image10.jpg 
convert image11.pfm image11.jpg 
convert image12.pfm image12.jpg 
convert image13.pfm image13.jpg 
convert image14.pfm image14.jpg 
convert image15.pfm image15.jpg 
convert image16.pfm image16.jpg 
convert image17.pfm image17.jpg 
convert image18.pfm image18.jpg 
